_current_task_id: 0
batch_size: 32
class_order:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
dataset: synbols
increment: 4
initial_increment: 0
known_task_boundaries_at_test_time: true
known_task_boundaries_at_train_time: true
nb_tasks: 12
num_workers: 4
relabel: false
smooth_task_boundaries: false
task_labels_at_test_time: false
task_labels_at_train_time: true
test_class_order:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
test_increment: 4
test_initial_increment: 4
test_transforms:
- to_tensor
- three_channels
train_transforms:
- to_tensor
- three_channels
transforms:
- to_tensor
- three_channels
- channels_first_if_needed
val_fraction: 0.2
val_transforms:
- to_tensor
- three_channels
